# Rust formatting configuration for enterprise-grade consistency
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_single_line = false
where_single_line = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
overflow_delimited_expr = false 